# Generated by Django 3.2.4 on 2021-06-03 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfileapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Uploadfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='images', max_length=255)),
                ('my_files', models.FileField(upload_to='')),
            ],
        ),
        migrations.DeleteModel(
            name='myuploadfile',
        ),
    ]
